### ISSUE TITLE
Allow chruby to auto-detect /opt/rubies/* and ~/.rubies/*

### ISSUE THREAD

**Issue by postmodern** [Atalanta/chef-chruby#1]
Since chruby 0.3.1, `share/chruby/chruby.sh` will initialize `RUBIES` using `/opt/rubies/*` and `~/.rubies/*`. Perhaps `chruby.sh.erb` should just append any additional Rubies?

```
<% if ::File.exists?("/opt/chef/embedded") -%>
RUBIES+=(/opt/chef/embedded)
<% end -%>
```

Thoughts?

**Comment by Atalanta** [comment]
Good plan.  I suspected it might.  However in my first experimenta, mixing the autodetected Rubies with the declared ones, I ended up over-writing the variable, so opted for explicitly declaring the whole list.  Appending is a much better idea.

**Comment by postmodern** [comment]
Not much of a provisioning expert, but should we favour explicit `RUBIES` over implicit?

**Comment by postmodern** [comment]
Also when adding dir globs to `RUBIES`, you should check if the glob isn't empty. If no files/directories match the glob, bash will resolve it to itself.

```
$ mkdir ~/.rubies/
$ RUBIES=(~/.rubies/*)
$ echo ${RUBIES[*]}
/home/hal/.rubies/*
```

You want to use:

```
<% unless Dir["~/.rubies/*"].empty? %>
  ...
<% end %>
```

**Comment by Atalanta** [comment]
What do you mean about favoring explicit over implicit?

Thanks for the glob tip - will release that shortly.

**Comment by Atalanta** [comment]
0.1.3 released, with the above improvements.

**Comment by postmodern** [comment]
@Atalanta well listing the contents of `RUBIES` explicitly might make for better documentation, when an admin reviews the config files. However, listing the paths explicitly might conflict with future versions of churby that might support auto-detecting other directories.

**Comment by Atalanta** [comment]
Right.  I think we can explain clearly and explicitly in the README.  I'd rather not do anything that interferes with your upstream development.  So I'm in favour of the approach we're now taking, of appending to the rubies array.  I'll probably push the logic into a helper method, and pass that to the template with the variables parameter, as it's a bit too much logic in the template right now, but that's a separate issue.
