### ISSUE TITLE
Chruby path is chruby-1 not chruby

### ISSUE THREAD

**Issue by atalanta-cookbooks** [Atalanta/chef-chruby#4]
On Ubuntu 13.04 (not yet tested elsewhere), using current version from community site:

```
ubuntu@ip-10-229-93-235:~$ ls -ld /usr/local/chruby*
drwxr-xr-x 8 root root 4096 Jun  1 14:50 /usr/local/chruby-1
```

This breaks because:

```
-bash: /usr/local/chruby/share/chruby/chruby.sh: No such file or directory
```

**Comment by Atalanta** [comment]
Could be a regression in the ark cookbook.  Am testing with ark from master.

**Comment by Atalanta** [comment]
OK - same issue in 'head'.

**Comment by Atalanta** [comment]
Added a symlink resource in the recipe as a workaround, while I work out what's happening with ark.

**Comment by Atalanta** [comment]
Update pushed to community site.
